name: Playwright Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # allows manual run from GitHub Actions tab

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1. Download your code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Install Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          
          # Cache Playwright browsers
      - name: Cache Playwright browsers
        uses: actions/cache@v3
        id: playwright-cache
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-playwright-

      # 3. Install your npm dependencies
      - name: Install dependencies
        run: npm ci

      # 4. Install Playwright browsers
      - name: Install Playwright browsers
        run: npx playwright install --with-deps chromium

      # 5. Run Playwright tests
      - name: Run Playwright tests
        run: npx playwright test

      # 6. Upload HTML test report (optional but useful)
        # even if tests fail, report is saved
      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results/
